### PR TITLE
Update Server.swift

### PR DESCRIPTION
**Pull request by surendratiwari3**
Changes to support the reconnect functionality if any mongoserver restarted in between of execution of process.

### CODE REVIEW

**Comment by lgaches** [comment]
I just push a fix. Could you check if it's working for you ?

**Comment by surendratiwari3** [comment]
yes its working with swift 3.0.1. tested on swift 3.0.1 completely.

you can use this functionality like this

let mongoServer = try Server(mongoURL: "mongodb://203.153.53.171:27017",automatically: true)

 if !mongoServer.isConnected
                {
                        log.info("MongoDB Server is Not Connected so Waiting For Server to Up")
                        //try mongoServer.disconnect()
                        try mongoServer.reconnect()
                        let customers =  mongoServer["samespace"]["customers"]
                        log.info("Server Connection Status (mongoServer.isConnected)")
                }

**Comment by lgaches** [comment]
Sorry, I mean MongoKitten 3.0.1.  A bug was preventing automatic reconnection. I just released this version.

**Comment by surendratiwari3** [comment]
its not automatic. you need to call reconnect function when you find connection is break

**Comment by surendratiwari3** [comment]
so my pull request is approved?

**Comment by surendratiwari3** [comment]
if you want i can do it automatically because right now i dont want to do it as per my requirement

**Comment by lgaches** [comment]
No. It's doesn't pass the tests. For reconnection a fix is already in MongoKitten 3.0.1 released yesterday. I'm not sure to understand the purpose of reconnect function. Thanks to find out the bug with reconnection.

**Comment by lgaches** [comment]
Please fill an issue with use case if MongoKitten 3.0.1 version does not comply with your requirements

**Comment by Joannis** [comment]
@surendratiwari3 I don't think reconnecting is a problem the user of MongoKitten has to deal with. I feel that MongoKitten should reconnect automatically.

**Comment by gabriellanata** [comment]
I agree with you Joannis. I had the same problem once, the MongoDB server restarted and MongoKitten did not automatically reconnect. I would even prefer the server to crash, because at least that way it is automatically restarted and the connection is fixed.

Does MongoKitten now reconnect automatically?

**Pull request closed without merging**
