### PR TITLE
raw value added in findAndModify

### PR DESCRIPTION
**Pull request by sujaykakkad**

### CODE REVIEW

**Comment by lgaches** [comment]
Thanks @sujaykakkad. Do you mind to add some tests to validate it ?

**Comment by sujaykakkad** [comment]
Where should I add it?

**Comment by lgaches** [comment]
In Tests/MongoKittenTests/CollectionTests.swift

**Comment by sujaykakkad** [comment]
I am trying to run test modules but it is giving me an error
```sh
fatal error: 'try!' expression unexpectedly raised an error: MongoKittenTests.TestManager.TestError.TestDataNotPresent: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-800.0.63/src/swift/stdlib/public/core/ErrorType.swift, line 178
```

**Comment by sujaykakkad** [comment]
I had cloned the repo then I used ```swift build``` then ```swift test```

**Comment by lgaches** [comment]
To run the tests you have to run mongodb and add zips.json dataset. You can run the script testprep.sh presents in Tools directory before running `swift test`

**Comment by sujaykakkad** [comment]
I added a test case for findAndModify.

**Comment by sujaykakkad** [comment]
Do I have to create another pull request?

**Pull request merged**
