### PR TITLE
List indexes

### PR DESCRIPTION
**Pull request by Joannis**
Added the ability to list indexes from a collection.

## How Has This Been Tested?
It's not, but it should be. I'd like to refer to #228 for now.

## Checklist:
- [x] If applicable, I have updated the documentation accordingly.
- [ ] If applicable, I have added tests to cover my changes.

### CODE REVIEW

**Comment by Andrewangeta** [comment]
Looks good!!

**Comment by Joannis** [comment]
@Andrewangeta Is this API as good as can be, in your opinion?

**Comment by Andrewangeta** [comment]
I think it's good and follows a similar API as `listCollections`.

**Comment by Joannis** [comment]
Can you merge & tag it? Since you're a member I _think_ you should be able to do it, but let's verify :)

**Comment by Andrewangeta** [comment]
Will do!

**Pull request merged**
